stages:

  extract_metadata:
    cmd:
    - python src/data/extract_metadata.py
    deps:
    - src/data/extract_metadata.py
    outs:
    - data/raw_metadata.xlsx:
        cache: true
        persist: false

  dicoms_to_rgb:
    cmd:
    - python src/data/convert_dicoms.py to_gray=false save_dir=data/sly_input_rgb
    deps:
    - src/data/convert_dicoms.py
    - data/raw_metadata.xlsx
    outs:
    - data/sly_input_rgb:
        cache: true
        persist: false

  dicoms_to_grayscale:
    cmd:
    - python src/data/convert_dicoms.py to_gray=true save_dir=data/sly_input_gray
    deps:
    - src/data/convert_dicoms.py
    - data/raw_metadata.xlsx
    outs:
    - data/sly_input_gray:
        cache: true
        persist: false

  stack_images:
    cmd:
    - python src/data/stack_images.py output_type=video save_dir=data/sly_input
    deps:
    - src/data/stack_images.py
    - data/sly_input_rgb
    - data/sly_input_gray
    outs:
    - data/sly_input:
        cache: true
        persist: false

  remove_images:
    deps:
    - data/sly_input
    cmd:
    - rm -rf data/sly_input_rgb || true
    - rm -rf data/sly_input_gray || true
    always_changed: true
