stages:

  # STAGE I
  extract_metadata:
    cmd:
    - echo "STAGE I"
    - rm data/raw_metadata.xlsx || true
    - python src/data/extract_metadata.py
    deps:
    - src/data/extract_metadata.py
    - data/dcm
    outs:
    - data/dcm_metadata.csv

  convert_dicoms:
    cmd:
    - rm -rf data/sly_input_rgb || true
    - rm -rf data/sly_input_gray || true
    - python src/data/convert_dicoms.py to_gray=false save_dir=data/sly_input_rgb
    - python src/data/convert_dicoms.py to_gray=true save_dir=data/sly_input_gray
    deps:
    - src/data/convert_dicoms.py
    - data/raw_metadata.xlsx
    outs:
    - data/sly_input_rgb:
        cache: false
    - data/sly_input_gray:
        cache: false

  stack_images:
    cmd:
    - rm -rf data/sly_input || true
    - python src/data/stack_images.py output_type=video save_dir=data/sly_input
    deps:
    - src/data/stack_images.py
    - data/sly_input_rgb
    - data/sly_input_gray
    outs:
    - data/sly_input

  # The pipeline is executed, regardless of whether its dependencies or outputs have actually changed
#  remove_images:
#    deps:
#    - data/sly_input
#    cmd:
#    - rm -rf data/sly_input_rgb || true
#    - rm -rf data/sly_input_gray || true
#    always_changed: true

  # STAGE II
  convert_sly_to_int:
    cmd:
    - echo "STAGE II"
    - rm -rf data/interim || true
    - python src/data/convert_sly_to_int.py
    deps:
    - src/data/convert_sly_to_int.py
    - data/sly_output
#    - data/sly_input    # Used to keep the stages in a strict order
    outs:
    - data/interim

  convert_int_to_cv:
    cmd:
    - rm -rf data/cv || true
    - python src/data/convert_int_to_cv.py
    deps:
    - src/data/convert_int_to_cv.py
    - data/interim
    - data/interim/metadata.xlsx
    outs:
    - data/cv
