name: oct
channels:
- conda-forge
- nodefaults
dependencies:
- pip=23.3
- python=3.11.6
- ffmpeg=6.0.0
- ffmpeg-python=0.2.0
- pip:
  - albumentations==1.3.1
  - clearml==1.13.1
  - dvc==3.27.0
  - dvc-gdrive==2.20.0
  - hpbandster==0.7.4
  - hydra-core==1.3.2
  - imutils==0.5.4
  - joblib==1.3.2
  - matplotlib==3.8.0
  - numpy==1.26.1
  - omegaconf==2.3.0
  - opencv-python==4.8.1.78
  - openpyxl==3.1.2
  - pandas==1.5.2
  - Pillow==9.5.0
  - pre-commit==3.5.0
  - pytest==7.4.2
  - pytorch_lightning==2.0.9
  - segmentation_models_pytorch==0.3.3
  - scikit-image==0.22.0
  - scikit-learn==1.3.1
  - scipy==1.11.3
  - supervisely
  - tensorboard==2.15.0
  - tomli==2.0.1
  - torch==2.1.0
  - tqdm==4.66.1
