name: oct
channels:
- conda-forge
- nodefaults
dependencies:
- pip=24.0
- python=3.11.8
- ffmpeg=6.0.0
- ffmpeg-python=0.2.0
- pip:
  - albumentations==1.4.3
  - dvc==3.49.0
  - dvc-gdrive==3.0.1
  - hydra-core==1.3.2
  - imutils==0.5.4
  - joblib==1.3.2
  - matplotlib==3.8.4
  - numpy==1.26.4
  - omegaconf==2.3.0
  - opencv-python==4.8.1.78
  - openpyxl==3.1.2
  - pandas==2.1.4
  - Pillow==10.2.0
  - pre-commit==3.7.0
  - pytorch_lightning==2.2.1
  - segmentation_models_pytorch==0.3.3
  - scikit-learn==1.4.1.post1
  - supervisely==6.73.62
  - tensorboard==2.16.2
  - tensorboardx==2.6.2.2
  - tifffile==2024.4.18
  - tomli==2.0.1
  - torch==2.2.2
  - tqdm==4.66.2
  - wandb==0.16.6
