defaults:
- main
- _self_

meta:
  study_dir: data/raw
  save_dir: data/raw

convert:
  study_dir: data/raw
  include_dirs: []
  exclude_dirs: []
  output_size: [1000, 1000]
  to_gray: false
  output_type: image         # image or video
  fps: 15
  save_dir: data/sly_input

sly_to_int:
  study_dir: data/sly_output
  crop: [[0, 0], [1000, 1000]]
  save_dir: data/interim

stack:
  study_dir: data/sly_input
  include_dirs: []
  exclude_dirs: []
  output_size: [1000, 1000]
  output_type: video         # image or video
  fps: 15
  save_dir: data/sly_input
