defaults:
- main
- _self_

data_dir: data/interim
save_dir: data/cv
save_color_mask: true
smooth_mask: true
num_folds: 5
seed: 11
split_column: study
class_names:
- Lumen
- Lipid core
- Fibrous cap
- Vasa vasorum
