defaults:
- main
- _self_

data_dir: data/interim
save_dir: data/cv
save_color_mask: true
smooth_mask: true
num_folds: 5
crop: [[125, 0], [875, 750]]  # [[x1,y1], [x2,y2]]
seed: 11
split_column: study
classes:
- Lumen
- Fibrous cap
- Lipid core
- Vasa vasorum
