defaults:
- main
- _self_

data_path: data/demo/input
save_dir: data/demo/output
model_dir: models/cascade_models
output_size: [1000, 1000]
device: auto
classes:
- Lumen
- Fibrous cap
- Lipid core
- Vasa vasorum
