defaults:
- main
- _self_

data_dir_1: data/sly_input_rgb
data_dir_2: data/sly_input_gray
include_dirs: []
exclude_dirs: []
output_size: [1000, 1000]
output_type: video         # image or video
fps: 15
save_dir: data/sly_input
