defaults:
- main
- _self_

project_name: OCT segmentation
data_dir: data/cv/fold_1
classes:
- Lumen
- Fibrous cap
- Lipid core
- Vasa vasorum
architecture: unet
encoder: resnet50
optimizer: Adam
lr: 0.001
input_size: 512
batch_size: 4
epochs: 75
device: auto  # cpu, gpu,  or auto
log_artifacts: true
wandb_save_media: true
save_dir: models
