defaults:
- main
- _self_

project_name: OCT segmentation
data_dir: data/final
classes: [Lipid core, Lumen, Fibrous cap, Vasa vasorum]
classes_color:
  Lipid core: [0, 252, 124]
  Lumen: [133, 21, 199]
  Fibrous cap: [170, 178, 32]
  Vasa vasorum: [34, 34, 178]
  Artifact: [152, 251, 152]
architecture: unet
encoder: resnet50
optimizer: Adam
lr: 0.001
input_size: 448
batch_size: 4
epochs: 75
device: auto
