defaults:
- main
- _self_

model_dir: models/Unet
data_dir: data/visualization
cam_method: LayerCAM # GradCAM, HiResCAM, GradCAMElementWise, GradCAMPlusPlus, XGradCAM, AblationCAM, EigenCAM, EigenGradCAM, LayerCAM
output_size: [1024, 1024]
device: auto  # cpu, gpu, or auto
save_dir: eval/activation_maps
